config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "homes#top"
  get "about" => "homes#about"
  resources :introductions  do
      resource :favorites, only: [:create, :destroy]
      resources :introduction_comments, only:[:create, :destroy]
    end
  resources "users", only: [:show, :edit, :update, :index]
  get "users/unsubscribe" => "users#unsubscribe"
  patch "users/withdraw" => "users#withdraw"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :introduction
end

app/models/introduction.rb
class Introduction < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :tag_maps, dependent: :destroy

  enum address_prefecture:{
   "---":0,
   北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
   茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
   新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
   岐阜県:21,静岡県:22,愛知県:23,三重県:24,
   滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
   鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
   徳島県:36,香川県:37,愛媛県:38,高知県:39,
   福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
   沖縄県:47
  }

end

app/models/introduction_comment.rb
class IntroductionComment < ApplicationRecord
  belongs_to :user
  belongs_to :introduction
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :introduction
  belongs_to
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :introductions, dependent: :destroy
  has_many :introduction_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :nickname])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
  end
  
  def destroy
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

  def index
  end

end

app/controllers/introduction_comments_controller.rb
class IntroductionCommentsController < ApplicationController
  
  def create
  end
  
  def destroy
  end
  
end

app/controllers/introductions_controller.rb
class IntroductionsController < ApplicationController

  def new
    @introduction = Introduction.new
  end

  def create
    @introduction = Introduction.new(introduction_params)
    @introduction.user_id = introduction_user.id
    @introduction.save
    redirect_to introductions_path
  end

  def show
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def introduction_params
    params.require(:introduction).permit(:place, :author, :title, :address_prefecture, :address_after_prefecture, :address_building_name, :introduction)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current.user
    @user.update(user_params)
    redirect_to user_path(params[:id])
  end

  def index
    @users = User.all
  end

  def unsubscribe
  end

  def withdraw
  end

private
  def user_params
    params.requier(:user).permit(:last_name, :first_name, :email, :nickname, :image_id, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/introduction_comments_helper.rb
module IntroductionCommentsHelper
end

app/helpers/introductions_helper.rb
module IntroductionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
概要を入力

app/views/homes/top.html.erb
投稿一覧をランキング形式で作成

app/views/introductions/new.html.erb
<div class="container">
  <h2>新規投稿画面</h2>
  <form>
    <%= form_with model:@introduction, url:new_introduction_path, local:true do |f| %>

      <div class="form-group row">
        <%= f.label :place, "スポット名" %><br />
        <%= f.text_field :place, autofocus: true %>
      </div>

      <div class="form-group row">
        <%= f.label :author, "作者名" %><br />
        <%= f.text_field :author, autofocus: true %>
      </div>

      <div class="form-group row">
        <%= f.label :title, "作品名" %><br />
        <%= f.text_field :title, autofocus: true %>
      </div>

      <div class="form-group row">
        <%= f.label :address_prefecture, "住所(都道府県)" %><br />
        <%= f.select :address_prefecture, Introduction.address_prefectures.keys, {} %>
      </div>

      <div class="form-group row">
        <%= f.label :address_after_prefecture, "住所(都道府県以降)" %><br />
        <%= f.text_field :address_after_prefecture, autofocus: true %>
      </div>

      <div class="form-group row">
        <%= f.label :address_building_name, "建物名" %><br />
        <%= f.text_field :address_building_name, autofocus: true %>
      </div>

      <div class="form-group row">
        <%= f.label :introduction, "紹介文" %><br />
        <%= f.text_field :introduction, autofocus: true %>
      </div>

      <div class="actions">
        <%= f.submit "保存する" %>
      </div>
    <% end %>
  </form>
</div>

app/views/layouts/_footer.html.erb
<div class="container mt-5">
  <div class="row mx-auto">
    <p>©CopyRight BookTrip.2021</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand navber-light bg-light">
  <a href="/" class="navber-brand">BookTrip</a>
  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Home", user_path(current_user.id), class:"nav-link active" %>
      </li>

      <li class="nav-item">
        <%= link_to "Introduction", introductions_path, class:"nav-link active" %>
      </li>

      <li class="nav-item">
        <%= link_to "logout", destroy_user_session_path, method: :delete, class:"nav-link active" %>
      </li>

    <% else %>
       <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link active" %>
      </li>

      <li class="nav-item">
        <%= link_to "About", about_path, class:"nav-link active" %>
      </li>

      <li class="nav-item">
        <%= link_to "新規登録", new_user_registration_path, class:"nav-link active" %>
      </li>

      <li class="nav-item">
        <%= link_to "ログイン", new_user_session_path, class:"nav-link active"%>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_info.html.erb
<%= attachment_image_tag user, :image, :fill, 200, 200, fallback: "no_image.jpg" %>

<table class="table">
  <% if user == current_user %>
    <tbody>
      <tr>
        <td>氏名</td>
        <td><%= user.last_name %><%= user.first_name %></td>
      </tr>
      <tr>
        <td>ニックネーム(表示名)</td>
        <td><%= user.nickname %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= user.email %></td>
      </tr>
      <tr>
        <td>紹介文</td>
        <td><%= user.introduction %></td>
      </tr>
    </tbody>
  <% else %>
    <tbody>
      <tr>
        <td>nickname</td>
        <td><%= user.nickname %></td>
      </tr>
      <tr>
        <td>introduction</td>
        <td><%= user.introduction %></td>
      </tr>
    </tbody>
  <% end %>
</table>
<div>
  <% if user == current_user %>
    <%= link_to '編集する', edit_user_path(user) %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2>マイページ</h2>

  <form>
    <%= form_with model:@user, url: users_path, local:true do |f| %>

      <%= attachment_image_tag @user, :image, :fill, 60, 60, fallback: "no_image.jpg"%>
      <label for="inputImage">ProfileImage</label>
      <%= f.attachment_field :image, placeholder: "プロフィール画像" %>

      <div class="form-group row">
        名字<%= f.text_field :last_name, autofocus: true %><br/>
      </div>

      <div class="form-group row">
        名前<%= f.text_field :first_name, autofocus: true %>
      </div>

      <div class="form-group row">
        <%= f.label :nickname, "ニックネーム(表示名)" %><br />
        <%= f.text_field :nickname, autofocus: true %>
      </div>

      <div class="form-group row">
        <%= f.label :email, "メールアドレス" %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="form-group row">
        <%= f.label :introduction, "紹介文" %><br />
        <%= f.text_field :introduction, autofocus: true %>
      </div>

      <div class="actions">
        <%= f.submit "保存する" %>
      </div>
    <% end %>
  </form>
</div>

app/views/users/show.html.erb
<h2>マイページ</h2>
<%= render 'info', user:@user %>